language: node_js

node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

script:
  - "npm run test"

branches:
  only:
    - master

after_success: 
  - bash <(curl -s https://codecov.io/bash)